"""Add amount to statement_history

Revision ID: cc8f8dc64e69
Revises: 
Create Date: 2026-03-02 17:38:18.689479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cc8f8dc64e69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_status_id'), table_name='payment_status')
    op.drop_table('payment_status')
    op.drop_index(op.f('ix_statement_history_id'), table_name='statement_history')
    op.drop_table('statement_history')
    op.drop_index(op.f('ix_payment_requests_account_no'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_id'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_reference'), table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_index(op.f('ix_msisdn_validations_id'), table_name='msisdn_validations')
    op.drop_table('msisdn_validations')
    op.drop_index(op.f('ix_payment_transactions_account_no'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_reference'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_payment_statuses_id'), table_name='payment_statuses')
    op.drop_table('payment_statuses')
    op.drop_index(op.f('ix_wallet_balances_id'), table_name='wallet_balances')
    op.drop_table('wallet_balances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_balances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_no', sa.VARCHAR(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('provider_response', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_no')
    )
    op.create_index(op.f('ix_wallet_balances_id'), 'wallet_balances', ['id'], unique=False)
    op.create_table('payment_statuses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reference', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('provider_response', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_payment_statuses_id'), 'payment_statuses', ['id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reference', sa.VARCHAR(), nullable=True),
    sa.Column('msisdn', sa.VARCHAR(), nullable=False),
    sa.Column('account_no', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('response', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_reference'), 'payment_transactions', ['reference'], unique=1)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_account_no'), 'payment_transactions', ['account_no'], unique=False)
    op.create_table('msisdn_validations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('msisdn', sa.VARCHAR(), nullable=False),
    sa.Column('is_valid', sa.VARCHAR(length=5), nullable=True),
    sa.Column('provider_response', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msisdn')
    )
    op.create_index(op.f('ix_msisdn_validations_id'), 'msisdn_validations', ['id'], unique=False)
    op.create_table('payment_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reference', sa.VARCHAR(), nullable=True),
    sa.Column('account_no', sa.VARCHAR(), nullable=True),
    sa.Column('msisdn', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('response', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_requests_reference'), 'payment_requests', ['reference'], unique=1)
    op.create_index(op.f('ix_payment_requests_id'), 'payment_requests', ['id'], unique=False)
    op.create_index(op.f('ix_payment_requests_account_no'), 'payment_requests', ['account_no'], unique=False)
    op.create_table('statement_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reference', sa.VARCHAR(), nullable=False),
    sa.Column('account_no', sa.VARCHAR(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('statement_data', sqlite.JSON(), nullable=True),
    sa.Column('provider_response', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_statement_history_id'), 'statement_history', ['id'], unique=False)
    op.create_table('payment_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reference', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('provider_response', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_payment_status_id'), 'payment_status', ['id'], unique=False)
    # ### end Alembic commands ###
